# name of the software
name: FECGSYN
# current version of the software
version: 1.2
# url of the download button
downloadUrl: https://github.com/fernandoandreotti/fecgsyn
# licence of the software
license: GNU General Public License v3.0
licenseUrl: http://www.gnu.org/licenses/gpl-3.0.en.html

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/fernandoandreotti/fecgsyn

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/fernandoandreotti/fecgsyn
  - title: Issues
    url: https://github.com/fernandoandreotti/fecgsyn/issues?state=open

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: mistic100
  repo: jekyll-bootstrap-doc

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: true
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap